import 'package:shagaf_ledger/core/common/entities/product.dart';

List<Product> products = [
  Product(
    id: 1,
    name: 'Atomic Habits',
    createdAt: DateTime.now(),
    currentInventory: 13,
    purchasePrice: 12.3,
    sellingPrice: 20,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
  Product(
    id: 2,
    name: 'Harry Potter',
    createdAt: DateTime.now(),
    currentInventory: 0,
    purchasePrice: 12.3,
    sellingPrice: 12,
  ),
  Product(
    id: 3,
    name: 'Clean Code',
    createdAt: DateTime.now(),
    currentInventory: 20,
    purchasePrice: 12.3,
    sellingPrice: 7,
  ),
];
